routes/access_tokens.go, routes/access_tokens_test.go
This takes our total test time from 5.05 seconds to 0.05 seconds.
=> Set OAuth token exchange timeout to 0 in tests

cli/main.go, client/client.go, routes/images.go, routes/images_test.go, routes/instances.go, routes/instances_test.go
If we support creation and finalisation of images from the client then
we can do everything for running draupnir from the one binary.
=> Support image create/finalise in client

client/client.go, main.go, routes/check_api_version.go, routes/check_api_version_test.go, spec/draupnir/health_check_spec.rb, version/version.go
Only reject requests that come from clients that are newer than the
server, or are running a different major version. This should be totally
fine as per semver rules, and will provide more flexibility to upgrade
the server without breaking clients.
The client also now doesn't inject an error if the server version
mismatches, and leaves the check up to the server. The API will return
an error that would otherwise be rendered, so we don't need to duplicate
the check in the client.
=> Semver match on Draupnir-Version header

Gopkg.lock, main.go, vendor/github.com/oklog/run/.gitignore, vendor/github.com/oklog/run/.travis.yml, vendor/github.com/oklog/run/LICENSE, vendor/github.com/oklog/run/README.md, vendor/github.com/oklog/run/example_test.go, vendor/github.com/oklog/run/group.go, vendor/github.com/oklog/run/group_test.go
It would be really useful for draupnir to listen on HTTP for connections
from the same box. This enables usage of the draupnir-client locally,
pointing at localhost for the connection, without having issues with
certificates.
=> Listen on http locally

cmd/draupnir-finalise-image
draupnir-finalise-image will currently fail if the upload is not in tar
format. This change allows a user to do their own custom upload of a
draupnir data directory, with whatever preparation step they wish to
perform, by only unpacking a tar file if we find one present.
This becomes really useful for people who wish to do the backup recovery
on the same machine as draupnir, as they can unpack the database and
recover from WAL files all inside the image upload directory.
=> Optionally unpack tar backup

cmd/draupnir-finalise-image
In future we probably want to provide a sample postgresql.conf when we create images. Right now though, hardcoding a 5GB limit is a Good Thing™
---
Specify a limit on temporary files to ensure a single instances doesn't
consume hundreds of GBs disk space.
=> Set temp_file_limit in postgresql.conf

routes/images_test.go, routes/instances_test.go
I think this makes these tests a little bit nicer. Somewhat sad that we're exactly even on line count, but you can't always win!
Also includes a change to bump the required Ruby version to 2.5.0
=> Minor test cleanup

CHANGELOG.md, cmd/draupnir-finalise-image
Running large anonymisation scripts writes loads of data to disk. One
thing that can significantly impact performance is the amount of WAL we
write to disk, and whether Postgres calls fsync to guarantee data
integrity after each write.
We can make finalisation much faster by disabling fsync (as we can
easily recreate a draupnir image from a backup, so we're not worried
about crash-safety here) and reducing the amount of data we write to our
WAL files.
We were previously using hot_standby WAL level, which meant we wrote all
the data required to power live read queries on a standby, which is
significantly more than the minimal/warm-standby level. We can change to
minimal for the anonymisation work, but should change back to
hot_standby for the live instances to ensure they better mirror …
=> Improve finalisation performance

cmd/draupnir-finalise-image
https://gocardless.myjetbrains.com/youtrack/issue/PT-2511
This commit handles the case when Postgres has some WAL to replay prior
to boot that might prevent createuser and other commands from executing
successfully. Instead we wait for up to 5m for archive recovery to
complete before trying to run the subsequent commands.
=> Wait for Postgres to boot in finalise

.gitignore, Makefile, README.md, Vagrantfile, dbconfig.yml, vagrant/anonymisation.sql, vagrant/draupnir.service, vagrant/draupnir_client_config.toml, vagrant/draupnir_config.toml, vagrant/example_db.sql, vagrant/provision.sh, vagrant/sudoers_draupnir
Developing draupnir is hard without a full environment set up. Using
Vagrant we can provide btrfs and a PostgreSQL server so that a locally
developed version of draupnir can run in a fully functional environment.
=> Add Vagrant VM for development

README.md, cmd/draupnir-create-instance, cmd/draupnir-finalise-image, cmd/draupnir/draupnir.go, pkg/exec/exec.go, pkg/models/instance.go, pkg/server/api/middleware/check_api_version.go, pkg/server/api/middleware/logger.go, pkg/server/api/middleware/middleware.go, pkg/server/api/routes/fakes.go, pkg/server/api/routes/fixtures.go, pkg/server/api/routes/instances.go, pkg/server/api/routes/instances_test.go, spec/draupnir/instance_spec.rb
https://gocardless.myjetbrains.com/youtrack/issue/PT-3043
When creating a new instance, generate a unique CA, server and client
certificate.
When the Draupnir client sets the environment up, retrieve the client
cert, key and CA from the instance directory and provision these on the
local machine, allowing for secure authentication with the instance.
---
I've also added some bugfixes into this PR, that I had to make in order to succesfully debug test failures, so it's probably worth viewing this commit-by-commit. I can pull these out into a separate PR if the reviewer prefers, but at the moment I feel like it makes sense to test as one chunk of work.
---
To test, perform the following steps:
```console
make build-linux
systemctl restart draupnir
eval $(/draupnir/draupnir.linux_amd64 …
```
=> Secure instances with client certificate auth

README.md, cmd/draupnir/draupnir.go, pkg/models/instance.go, pkg/server/api/routes/fixtures.go, pkg/server/api/routes/instances_test.go, pkg/server/config/config.go, pkg/server/server.go, pkg/store/instances.go, spec/draupnir/instance_spec.rb, spec/fixtures/config.toml, vagrant/draupnir_config.toml
This allows us to split the API hostname and the hostname used to
connect to Postgres instances, because we can't route Postgres traffic
through the same load balancer as the API requests.
By having the server-side set the hostname that the client should
connect to, we lay the foundations for scaling Draupnir to more than one
node too.
=> Allow configuration of an instance hostname

migrations/2019-06-19_16-47_add_refresh_token_to_instances.sql, pkg/exec/exec.go, pkg/models/instance.go, pkg/server/api/auth/auth.go, pkg/server/api/auth/fake.go, pkg/server/api/middleware/authenticate.go, pkg/server/api/middleware/authenticate_test.go, pkg/server/api/routes/fakes.go, pkg/server/api/routes/images_test.go, pkg/server/api/routes/instances.go, pkg/server/api/routes/instances_test.go, pkg/server/cleaner.go, pkg/server/config/config.go, pkg/server/server.go, pkg/store/instances.go, spec/fixtures/bootstrap, spec/fixtures/config.toml, structure.sql, vagrant/draupnir_config.toml
Store the users refresh token along with their instances so that we can
periodically test the refresh tokens validity and clean out old
instances. A refresh token is invalid if the user is suspended, deleted,
or they revoke the applications access.
=> Clean up old instances

README.md, pkg/models/instance.go, pkg/server/api/routes/instances.go, pkg/server/api/routes/instances_test.go, pkg/server/config/config.go, pkg/server/server.go, spec/fixtures/config.toml, vagrant/draupnir_config.toml
f0fbb83: Allow configuration of instance port range
This helps when defining a firewall range to open up access to the
Postgres instances.
8886728: Decrease the potential for port collisions
Currently there is a high chance of collisions when booting a new
Draupnir instance. As per the birthday problem formula, if there are 10
instances running, with a port range of 1000 ports, then we've got a 10%
chance of colliding. When this happens the instance fails to start, and
the user is returned an unhelpful error about an internal server error.
To resolve this, two changes have been made:
1. The random number generator is seeded with nanoseconds, rather than
just seconds, which helps us in the case of two requests that arrive
within the same second.
2. The list of existing instances is …
=> Allow configuration of instance port range

cmd/draupnir-finalise-image
Make sure to explicitly ban SSLv2 and SSLv3 (although the system
configuration already prevented these), as well as ensuring that TLSv1.2
and above are the only supported versions.
Additionally restrict the cipher suites that are available to use; this
effectively removes the ciphers which employed SHA-1 from the list.
The resulting cipher suites, according to `sslyze --sslv2 --sslv3
--tlsv1 --tlsv1_1 --tlsv1_2 localhost:xxxx --starttls=postgres
--hide_rejected_ciphers` is:
```
Preferred:
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384             ECDH-256 bits  256 bits
Accepted:
ARIA128-GCM-SHA256                                -              128 bits
ARIA256-GCM-SHA384                                -              256 bits
DHE-RSA-ARIA128-GCM-SHA256                        -              128 bits …
```
=> Update TLS cipher suite configuration

cmd/draupnir-create-instance
The security of instances currently depends on the fact that an image
has been finalised with a `hostssl ... trust clientcert=1` line in the
`pg_hba.conf`.
Without this line present, and in the correct format, it'd be possible
for anyone to connect to an instance without providing credentials.
As an additional verification step, add checks at instance-creation time
that ensure that it's not possible to connect to an instance without
TLS, or without providing a client certificate. While these checks are
being performed, the instance is listening on the local interface only,
and therefore is inaccessible to external users.
If these checks fails then the instance is shut down and the
provisioning process returns an error, which will be sent back to the
client and trigger a Sentry.
=> Verify instance auth settings upon creation

README.md
Add the `clean_interval` config option to the configuration section of the readme as well as add a but about cleaning users instances to the security model section.
=> Add instance cleaning to the README

cmd/draupnir-create-instance, cmd/draupnir-destroy-instance, cmd/draupnir-finalise-image, spec/fixtures/bootstrap, vagrant/provision.sh
To improve security and better isolate the instances we should change the user that the draupnir postgres instances run as. 
They currently run as `postgres` and this PR changes them to run as a new user called `draupnir-instance`.
We don't use the existing draupnir user as that user is used to run the draupnir api server which has read access to each instances client certificates.
=> Don't run draupnir instances as the postgres user

cmd/draupnir-create-instance, cmd/draupnir-finalise-image, cmd/draupnir/draupnir.go, vagrant/example_db.sql
During the security review of the system concerns were raised about the
ability to connect to the Draupnir instances via the `postgres` user,
which has superuser privileges.
This is an issue because this user can use superuser-level functions to
do things like read file contents, and load extensions which may contain
malicious code.
To resolve this, make the following changes:
- Only allow connections from a `draupnir` user, which is added at
image-finalisation time.
- Reassign all objects in all databases to the `draupnir` user, so that
it has permissions to create, delete, alter etc all existing objects.
- Perform the instance verification checks with the `draupnir` user,
rather than `postgres`.
Given that we now only allow connections from a single user, also change
the authentication …
=> Only allow instance connections from non-superuser

cmd/draupnir/draupnir.go, pkg/server/api/routes/access_tokens.go, pkg/server/api/routes/access_tokens_test.go
This will improve the UX for users who somehow lose their existing token
(e.g. they get a new laptop). We take the approach suggested by Google [here](https://developers.google.com/identity/protocols/OAuth2WebServer#tokenrevoke).
=> Revoke existing tokens when re-authing

CHANGELOG.md, README.md, cmd/draupnir/draupnir.go, pkg/server/config/config.go, pkg/server/server.go, spec/fixtures/config.toml, vagrant/draupnir.service, vagrant/draupnir_client_config.toml, vagrant/draupnir_config.toml, vagrant/provision.sh
e14b35c: Improve configuration of listen addresses
In the current state there is an 'insecure' port, which is bound to
localhost only, and a 'secure' port that listens on all interfaces.
The secure port only accepts requests that have negotiated a connection
over TLS (using the certificate/key pair provided to Draupnir), whereas
the insecure port uses plain HTTP.
There's a few issues with this:
1. It's not possible to disable either the secure or insecure ports.
2. It's not possible to make the insecure server available on any
interface other than localhost, even if you have firewall rules that
mitigate that being a potential issue.
3. It's not possible to specify the address (and therefore interface)
that the secure server listens, making it available to anything on
the machine.
In our …
=> Allow better configuration of listen addresses

cmd/draupnir-finalise-image, cmd/draupnir-start-image
For those doing image preparation from the draupnir box locally, you
might want to ask draupnir to boot the image for you to run custom
anonymisation scripts or whatever prep you might choose outside of the
finalise step.
There's no safe way to request the finalise step executes a script
locally, so split the behaviour between two different stages. A
following commit will expose the start image functionality via the API
and CLI.
=> Separate image boot from finalise

pkg/server/api/middleware/error_handler.go, pkg/server/api/middleware/logger.go
Sadly, we log them here too. Remove the error logging as it's already
included in the request log anyway, and we don't want to log tokens.
=> Remove another place we log access tokens

.circleci/config.yml
This should help with installing an older version of ruby.
When I cut this branch from the master branch, even though they were up to date, the integration test was failing
=> CI-1488: Downgrade Ubuntu version for CircleCI

spec/fixtures/README.md
This PR describes how to update the `db.tar` file just in case we need
to upgrade draupnir's PG version so we can get integration tests to run
again.
=> CI-1488: How to update db.tar file

.circleci/config.yml
Currently, goreleaser is using an out of date version trying to build for darwin with the 386 arch, and failing to do so.
[v0.156.0](https://github.com/goreleaser/goreleaser/releases/tag/v0.156.0) seems to address that
=> quick: Update goreleaser to a more modern version

.circleci/config.yml, .goreleaser.yml
Tested the config locally with that goreleaser version by running:
```sh
goreleaser check
```
Seems to like the current configuration. Making this update as npfm
files was deprecated
[Info on that](https://goreleaser.com/deprecations/?h=nfpms+files#nfpmsfiles)
=> quick: Updating goreleaser to 1.10.2

.github/dependabot.yml, go.mod, go.sum, pkg/client/config/config.go, pkg/server/config/config.go
No private repositories are used for dependabot, so we shouldn't
require access to private registries.
The go.mod change is made on the back of dependabot's suggestion so the file registers as valid. The way the toml module was required also had to be updated to match casing, as suggested by `go mod tidy`
Added screenshots of dependabot errors as those would hopefully go away once this PR gets merged in
For the env var issues we're seeing for ruby and docker, it's because I have set up dependabot to include private registries, but those env vars are only available on private repositories of GoCardless, not public ones, for security concerns.
The go.mod change is just a casing mismatch
=> Chore: Update dependabot configuration to not use private registry creds

.github/dependabot.yml
I had incorrectly assumed this was a public registry, and thus did not
require a definition at the top of the file, but it turns out it's not
=> Remove trailing mention of docker registry

README.md, cmd/draupnir-finalise-image
Need to upgrade dependencies but ran into test issues
Tests were failing with:
```
13 examples, 5 failures
Failed examples:
rspec ./spec/draupnir/instance_spec.rb:67 # /instances POST /instances creates the instance if given a ready image
rspec ./spec/draupnir/instance_spec.rb:117 # /instances GET /instances returns a JSON payload showing the instance
rspec ./spec/draupnir/instance_spec.rb:143 # /instances GET /instances/:id shows the given instance
rspec ./spec/draupnir/instance_spec.rb:184 # /instances GET /instances/:id returns the correct credentials for a given instance
rspec ./spec/draupnir/instance_spec.rb:208 # /instances DELETE /instances/:id deletes the instance and returns a 204
make: *** [Makefile:26: test-integration] Error 1
```
When container is built it is running tests …
=> [Pdfr-43151] Fix failing tests for draupnir
